### ISSUE TITLE
Missing styles-component

### ISSUE THREAD

**Issue by chiragBorkarEV** [erikras/audiocard#2]
Latest release is giving error of 'missing styles-component' package. I installed it using yarn.
So I added missing dependency separately to get it worked.
Please address this issue in next release.

Thanks

**Comment by erikras** [comment]
I intentionally [moved `styled-components` to be a peer dependency](https://github.com/erikras/audiocard/blob/master/package.json#L25) to:
1. reduce bundle size
1. allow consumer to use whatever version they want that matches the semver requirement

Reopen if you still think this is a problem.

**Comment by boxabirds** [comment]
@erikras I'm an npm n00b so apologies if this is wrong but could you possibly add styled-components as a peerDependency? Currently it's not listed. 

`npm info styled-components peerDependencies
{ react: '>= 16.3.0', 'react-dom': '>= 16.3.0' }`
